#---------------------------------#
# Info of configure the PM-plugin #
#---------------------------------#
# @author  : PresentKim
# @version : 1.1.0
# @url     : https://github.com/organization/ExamplePlugin-AppVeyor/blob/master/appveyor.yml

#---------------------------------#
#      general configuration      #
#---------------------------------#
# version format
version: "#{build}"

# branches to build
branches:
  # whitelist
  only:
    - master

# Skipping commits with particular message or from specific user
skip_commits:
  files:
    - README.md

# Maximum number of concurrent jobs for the project
max_jobs: 1


#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Ubuntu1804

# set clone depth
clone_depth: 5

# environment variables
environment:
  APPVEYOR_BUILD_URL: "https://ci.appveyor.com/project/${APPVEYOR_ACCOUNT_NAME}/${APPVEYOR_PROJECT_NAME}/builds/${APPVEYOR_BUILD_ID}"
  BUILD_SCRIPT_URL: "https://raw.githubusercontent.com/organization/ExamplePlugin-AppVeyor/master/build.php"

# build cache to preserve files/folders between builds
cache:
  - '$HOME/cache/' # my cache

# scripts that are called at very beginning, before repo cloning
init:
  - mkdir $HOME/cache/

# scripts that run after cloning repository
install:
  - wget -nc -P $HOME/cache/ https://jenkins.pmmp.io/job/PHP-7.3-Linux-x86_64/lastSuccessfulBuild/artifact/PHP_Linux-x86_64.tar.gz
  - tar -C ../ -xvf $HOME/cache/PHP_Linux-x86_64.tar.gz
  - wget --cache=off --cookies=off ${BUILD_SCRIPT_URL}

# to run your custom scripts instead of automatic MSBuild
build_script:
  - ../bin/php7/bin/php ./build.php --buildurl=${APPVEYOR_BUILD_URL} --buildnum=${APPVEYOR_BUILD_NUMBER}


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: "releases/*.phar"